-- 7. Audit Logs Table (관리자 활동 로그)
create table audit_logs (
  id bigint generated by default as identity primary key,
  admin_username text not null,
  action text not null, -- 'UNLOCK_WEEK', 'LOCK_WEEK'
  target_week text not null, -- 'YYYY-MM-DD'
  details text,
  created_at timestamptz default now()
);

-- 8. Enable RLS for Audit Logs
alter table audit_logs enable row level security;
create policy "Enable insert for all users" on audit_logs for insert with check (true);
create policy "Enable select for admins" on audit_logs for select using (true);
