-- 1. Users Table (사용자 및 관리자 정보)
create table app_users (
  username text primary key,
  password text not null, -- MVP라 평문 저장 (추후 암호화 권장)
  role text default 'staff', -- 'admin' or 'staff'
  type text default 'Casual', -- 'Full-time', 'Part-time', 'Casual'
  order_index int default 999,
  is_default_password boolean default true,
  created_at timestamptz default now()
);

-- 2. Shifts Table (스케줄 데이터)
create table shifts (
  id bigint generated by default as identity primary key,
  username text references app_users(username) on delete cascade,
  date text not null, -- 'YYYY-MM-DD'
  type text not null, -- 'lunch' or 'dinner'
  status text not null, -- 'unavailable', 'available', etc.
  updated_at timestamptz default now(),
  unique(username, date, type) -- 중복 방지 (Upsert용)
);

-- 3. Settings Table (잠금 주간 등 전역 설정)
create table app_settings (
  key text primary key,
  value jsonb
);

-- 4. 초기 데이터 (관리자 계정)
insert into app_users (username, password, role, is_default_password)
values 
('Cathy', '1234', 'admin', true),
('staff', '1234', 'staff', true)
on conflict (username) do nothing;

-- 5. 초기 설정 (잠금 목록 초기화)
insert into app_settings (key, value)
values ('locked_weeks', '[]'::jsonb)
on conflict (key) do nothing;

-- 6. 보안 정책 (Row Level Security) - MVP라 일단 모두 허용 (선택사항)
alter table app_users enable row level security;
alter table shifts enable row level security;
alter table app_settings enable row level security;

create policy "Enable all access for all users" on app_users for all using (true) with check (true);
create policy "Enable all access for all users" on shifts for all using (true) with check (true);
create policy "Enable all access for all users" on app_settings for all using (true) with check (true);
